version: '3'
services:
web:
  build:  
    context:   
  depends_on:
    - db
  image: tomcat
  volumes:
     - ./target/LoginWebApp.war:/usr/local/tomcat/webapps/LoginWebApp.war
  ports:
    - '8082:8080'
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: testdb1
    MYSQL_USER: testuser
    MYSQL_PASSWORD: root    